# Perfil activo cuando se ejecuta en contenedor Docker
# Las variables de entorno las inyecta docker-compose

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}

app.resend.api-key=${APP_RESEND_API_KEY}
