# Server
server.port=8080

# Application
spring.application.name=bandsync

# MongoDB
spring.data.mongodb.uri=mongodb+srv://BandSync:Reimon87654.@bandsync-cluster.7ljap4a.mongodb.net/bandsync_db?appName=bandsync-cluster

# Logging
logging.level.com.bandsync=DEBUG

# JWT
app.jwt.secret=app.jwt.secret=nv9+/cXvSR3zt84mKsN8HBzFPHsgmM5X5q/gYKwPkrkEyUdhqc4KMCkHAv8QoQKpCb6J/5kVubKc0RkVokCO4g==
app.jwt.expiration=28800000

# Resend
app.resend.api-key=re_QpWYVrU3_d8zxBfXyLcjBVcRAW2hK4RhH

# Perfil activo (para cargar datos de prueba)
spring.profiles.active=dev
